#!/bin/bash -e

MASTERPASS=supersecret
#$(mcookie | cut -b 1-8)

cat > /etc/inithooks.conf <<EOF
export ROOT_PASS=${MASTERPASS}
export USER_PASS=${MASTERPASS}
export APP_EMAIL=no@o.ne
export APP_PASS=${MASTERPASS}
export SEC_ALERTS=no@o.ne
export SEC_UPDATES=SKIP
export HUB_APIKEY=SKIP
EOF
