#!/bin/sh

mode=`cat /proc/cmdline | awk -F'bitkey=' '{ print $2 }' | cut -f 1 -d ' '`
CONFIG=/home/user/.wbar

cat >$CONFIG<<EOF
i: /usr/share/pixmaps/wbar/dock.png
c: wbar --bpress --pos bottom --zoomf 1.3 --isize 52 --idist 3 --jumpf 1 --nanim 3 --balfa 25
t: /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf/10

i: /usr/local/share/icons/electrum.png
c: electrum-wrapper $mode >/dev/null
t: Electrum ($mode)

i: /usr/share/icons/hicolor/48x48/apps/wassabee.png
c: wassabee
t: Wasabi Wallet

EOF

if [ ! "$mode" = "cold-offline" ]; then
cat >>$CONFIG<<EOF
i: /usr/share/icons/hicolor/48x48/apps/whirlpool-gui.png
c: /opt/whirlpool-gui/whirlpool-gui
t: Samourai Whirlpool

i: /usr/share/icons/hicolor/48x48/apps/brave-browser.png
c: brave-wrapper
t: Web browser

i: /usr/share/icons/nuoveXT2/48x48/places/network-server.png
c: xterm -e 'sudo nmtui'
t: Network Configuration

EOF
fi

cat >>$CONFIG<<EOF
i: /usr/local/share/icons/wallet.png
c: brave-offline-app file:///usr/local/share/cryptojsappslauncher/offline.html
t: Offline Web Apps

i: /usr/share/pixmaps/qtqr.png
c: qtqr
t: QR scanner

i: /usr/share/icons/nuoveXT2/48x48/apps/utilities-terminal.png
c: lxterminal
t: terminal

i: /usr/share/icons/nuoveXT2/48x48/apps/text-editor.png
c: gedit
t: editor

i: /usr/share/icons/nuoveXT2/48x48/devices/input-keyboard.png
c: onboard
t: keyboard

i: /usr/share/icons/nuoveXT2/48x48/apps/system-file-manager.png
c: thunar /media
t: file manager

i: /usr/share/icons/nuoveXT2/48x48/actions/system-shutdown.png
c: shutdown-prompt
t: shutdown

EOF
