#!/bin/bash

mode=`cat /proc/cmdline | awk -F'bitkey=' '{ print $2 }' | cut -f 1 -d ' '`

if [ "$mode" = "cold-offline" ] ; then
    cd /usr/lib/modules/`uname -r`/kernel/drivers/net

    for type in ethernet wireless ; do 
        modules=`find ${type} -type f -name '*.ko' -exec basename {} \; | cut -f 1 -d '.'`
    
        # unload all {ethernet,wireless} drivers from the kernel
        for m in $modules ; do
           rmmod -f ${m}
        done;
    
        # remove all {ethernet,wireless} drivers from filesystem
        find ${type} -type f -name '*.ko' -exec rm -f {} \;

    done; 
fi
